# Generated by Django 3.0.7 on 2020-06-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
