# Generated by Django 3.0.7 on 2020-07-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Head',
        ),
        migrations.RemoveField(
            model_name='events_interested',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='events_interested',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='events_interested',
        ),
    ]
