# Generated by Django 3.0.7 on 2020-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('Rollno', models.IntegerField()),
                ('college', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=40)),
            ],
        ),
    ]
